//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceKpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPMInstTasks
    {
        public int TaskID { get; set; }
        public string ProcessName { get; set; }
        public string OwnerAccount { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> FinishAt { get; set; }
        public string State { get; set; }
        public string AgentAccount { get; set; }
        public string SerialNum { get; set; }
        public string OptUser { get; set; }
        public Nullable<System.DateTime> OptAt { get; set; }
        public string OptMemo { get; set; }
        public Nullable<int> FormDataSetID { get; set; }
        public Nullable<int> ExtYear { get; set; }
        public string ExtInitiator { get; set; }
        public Nullable<bool> ExtDeleted { get; set; }
        public Nullable<int> OwnerPositionID { get; set; }
        public Nullable<int> ParentTaskID { get; set; }
        public Nullable<int> ParentStepID { get; set; }
        public string ParentStepName { get; set; }
        public string ProcessVersion { get; set; }
        public string ParentServerIdentity { get; set; }
        public Nullable<bool> ReturnToParent { get; set; }
    }
}
