//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceKpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPMInstProcSteps
    {
        public int StepID { get; set; }
        public int TaskID { get; set; }
        public string ProcessName { get; set; }
        public string NodeName { get; set; }
        public string OwnerAccount { get; set; }
        public System.DateTime ReceiveAt { get; set; }
        public Nullable<System.DateTime> FinishAt { get; set; }
        public string SelAction { get; set; }
        public bool Share { get; set; }
        public string Memo { get; set; }
        public bool HumanStep { get; set; }
        public string AgentAccount { get; set; }
        public string HandlerAccount { get; set; }
        public string SubNodeName { get; set; }
        public bool AutoProcess { get; set; }
        public string Comments { get; set; }
        public Nullable<int> UsedMinutes { get; set; }
        public Nullable<int> UsedMinutesWork { get; set; }
        public Nullable<int> RecedeFromStep { get; set; }
        public int TimeoutNotifyCount { get; set; }
        public Nullable<int> RisedConsignID { get; set; }
        public Nullable<int> BelongConsignID { get; set; }
        public string ConsignOwnerAccount { get; set; }
        public Nullable<System.DateTime> TimeoutFirstNotifyDate { get; set; }
        public Nullable<System.DateTime> TimeoutDeadline { get; set; }
        public Nullable<int> StandardMinutesWork { get; set; }
        public bool BatchApprove { get; set; }
        public bool Posted { get; set; }
        public bool FormSaved { get; set; }
        public Nullable<int> ParentStepID { get; set; }
        public string NodePath { get; set; }
        public Nullable<int> ExtYear { get; set; }
        public Nullable<int> ExtStepYear { get; set; }
        public string ExtRecipient { get; set; }
        public bool ExtDeleted { get; set; }
        public Nullable<int> OwnerPositionID { get; set; }
        public string ProcessVersion { get; set; }
    }
}
