//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceKpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPMSysUsers
    {
        public string Account { get; set; }
        public string Password { get; set; }
        public bool SysUser { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string HRID { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string Office { get; set; }
        public string CostCenter { get; set; }
        public string OfficePhone { get; set; }
        public string HomePhone { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
        public string WWWHomePage { get; set; }
        public string Location { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public string 家庭电话 { get; set; }
        public string SID { get; set; }
        public string LogonProvider { get; set; }
        public bool Disabled { get; set; }
        public string NameSpell { get; set; }
        public string ContractDept { get; set; }
        public string Url { get; set; }
        public string IsBinding { get; set; }
        public string Secretary { get; set; }
        public string Others { get; set; }
    }
}
