//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceKpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iAsset
    {
        public int TaskID { get; set; }
        public string FormNo { get; set; }
        public string Account { get; set; }
        public string AgentAccount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AppLevel { get; set; }
        public string AppName { get; set; }
        public string AppID { get; set; }
        public string AppDepartment { get; set; }
        public string AppPosition { get; set; }
        public string AgentName { get; set; }
        public string AgentID { get; set; }
        public string AgentDepartment { get; set; }
        public string AgentPosition { get; set; }
        public string Operation { get; set; }
        public string Type { get; set; }
        public string FundingAccount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string UseDirection { get; set; }
        public string EquipmentSource { get; set; }
        public string Country { get; set; }
        public string SupplyCompany { get; set; }
        public Nullable<int> IsTaxFee { get; set; }
        public string InvoiceNumber { get; set; }
        public string FactoryName { get; set; }
        public string FactoryNumber { get; set; }
        public Nullable<System.DateTime> FactoryDate { get; set; }
        public string ArgumentNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Performance { get; set; }
        public string Applicability { get; set; }
        public string Feature { get; set; }
        public string Attachment { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public string BusinessCode { get; set; }
    }
}
