//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceKpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iAssetDetail
    {
        public int Id { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string FixedAssetId { get; set; }
        public string Name { get; set; }
        public string Specification { get; set; }
        public string Type { get; set; }
        public string Department { get; set; }
        public string DepartmentCode { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string EduCode { get; set; }
        public string FinCode { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string KeeperAccount { get; set; }
        public string Keeper { get; set; }
        public string ResponsiblerAccount { get; set; }
        public string Responsibler { get; set; }
        public string FeeSourceName { get; set; }
        public string FeeSourceCode { get; set; }
        public string FeeSourceCodeName { get; set; }
        public string FixedFundCode { get; set; }
        public string AccumulationItem { get; set; }
        public string AccountCode { get; set; }
    }
}
