//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceKpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iOutside
    {
        public int TaskID { get; set; }
        public string FormNo { get; set; }
        public string Account { get; set; }
        public string AgentAccount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AppLevel { get; set; }
        public string AppName { get; set; }
        public string AppID { get; set; }
        public string AppDepartment { get; set; }
        public string AppPosition { get; set; }
        public string AgentName { get; set; }
        public string AgentID { get; set; }
        public string AgentDepartment { get; set; }
        public string AgentPosition { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Destination { get; set; }
        public string Description { get; set; }
        public string PayeeID { get; set; }
        public string Payee { get; set; }
        public string Name { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string TravelsFormNo { get; set; }
        public string IsFlag { get; set; }
        public string PaymentTerm { get; set; }
        public string AlolwanceTypes { get; set; }
        public string AlolwanceType { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<decimal> iFare { get; set; }
        public Nullable<decimal> iToll { get; set; }
        public Nullable<decimal> iParking { get; set; }
        public Nullable<decimal> iOthers { get; set; }
        public Nullable<decimal> iTotalAmount { get; set; }
        public string iCapital { get; set; }
        public Nullable<decimal> oSubsidy { get; set; }
        public Nullable<decimal> oFare { get; set; }
        public Nullable<decimal> oAirFare { get; set; }
        public Nullable<decimal> oHotelFee { get; set; }
        public Nullable<decimal> oFreight { get; set; }
        public Nullable<decimal> oPostage { get; set; }
        public Nullable<decimal> oOthers { get; set; }
        public Nullable<decimal> oTotalAmount { get; set; }
        public string oCapital { get; set; }
        public string Attachment { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string BankItem { get; set; }
        public string Summary { get; set; }
        public string HistoryTaskid { get; set; }
        public string HistoryTaskids { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<decimal> FirstPayAmount { get; set; }
        public string PayCapital { get; set; }
        public string IsBind { get; set; }
        public string TemporaryName { get; set; }
        public string PayeeLevel { get; set; }
        public string MemberType { get; set; }
        public string CostType { get; set; }
        public Nullable<int> CostID { get; set; }
        public string ItemName { get; set; }
        public string ContractName { get; set; }
        public string ESOContractName { get; set; }
        public string LLCContractName { get; set; }
        public Nullable<long> ContractTaskID { get; set; }
        public Nullable<long> ContractTaskIDS { get; set; }
        public string CourseName { get; set; }
        public string Secretary { get; set; }
        public string PayeeAccount { get; set; }
        public string MailorNot { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public string PZNO { get; set; }
        public string EMBAContractName { get; set; }
        public string EDPContractName { get; set; }
        public string DBAContractName { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> test { get; set; }
        public string cCode { get; set; }
        public string cVenCode { get; set; }
        public string cPayCode { get; set; }
        public string DepartmentCode { get; set; }
        public string CAFRProjectNo { get; set; }
        public string ShortTerm { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> PayAmountRMB { get; set; }
        public Nullable<decimal> oMeal { get; set; }
        public Nullable<decimal> oHospitality { get; set; }
        public string BankID { get; set; }
        public string STATENAME { get; set; }
        public string CITYNAME { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> Addition { get; set; }
        public Nullable<decimal> FinalRMB { get; set; }
        public string eInvoice { get; set; }
        public string eInvoiceNum { get; set; }
        public string VendorEmail { get; set; }
    }
}
