//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceKpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iReimbursement
    {
        public Nullable<int> TaskID { get; set; }
        public string FormNo { get; set; }
        public string Account { get; set; }
        public string AgentAccount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AppLevel { get; set; }
        public string AppName { get; set; }
        public string AppID { get; set; }
        public string AppDepartment { get; set; }
        public string AppPosition { get; set; }
        public string AgentName { get; set; }
        public string AgentID { get; set; }
        public string AgentDepartment { get; set; }
        public string AgentPosition { get; set; }
        public string Referee { get; set; }
        public string Attribute { get; set; }
        public string Attribute1 { get; set; }
        public string PaymentTerm { get; set; }
        public string PaymentTerms { get; set; }
        public string IsFlag { get; set; }
        public string Company { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string PayeeID { get; set; }
        public string Payee { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CurrencyTips { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalAmountRMB { get; set; }
        public string Capital { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string ContractDept { get; set; }
        public string Flag { get; set; }
        public string BankItem { get; set; }
        public string RefereeAccount { get; set; }
        public string Summary { get; set; }
        public string HistoryTaskids { get; set; }
        public string Attachment { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<decimal> FirstPayAmount { get; set; }
        public string PayCapital { get; set; }
        public Nullable<decimal> CjdAmount { get; set; }
        public string IsBind { get; set; }
        public string TemporaryName { get; set; }
        public string PayeeLevel { get; set; }
        public string MemberType { get; set; }
        public string CostType { get; set; }
        public Nullable<int> CostID { get; set; }
        public string ItemName { get; set; }
        public string ContractName { get; set; }
        public string ESOContractName { get; set; }
        public string LLCContractName { get; set; }
        public Nullable<long> ContractTaskID { get; set; }
        public Nullable<long> ContractTaskIDS { get; set; }
        public string CourseName { get; set; }
        public string Secretary { get; set; }
        public string MailorNot { get; set; }
        public string PayeeAccount { get; set; }
        public string ProjectNo { get; set; }
        public string PZNO { get; set; }
        public Nullable<int> PRTaskID { get; set; }
        public Nullable<int> SATaskID { get; set; }
        public string SupplierName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string RType { get; set; }
        public string DisplayPRNo { get; set; }
        public string LongTerm { get; set; }
        public string EMBAContractName { get; set; }
        public string EDPContractName { get; set; }
        public string EDPFinalContract { get; set; }
        public Nullable<int> TaskID4Import { get; set; }
        public string DBAContractName { get; set; }
        public Nullable<decimal> AcutalAmount { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> test { get; set; }
        public string Type { get; set; }
        public string cCode { get; set; }
        public string cRdCode { get; set; }
        public string cVenCode { get; set; }
        public string DepartmentCode { get; set; }
        public string cPayCode { get; set; }
        public string CAFRProjectNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string ShortTerm { get; set; }
        public string BankID { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string BankItemName { get; set; }
        public string SJTUAccountCode { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> Addition { get; set; }
        public Nullable<decimal> FinalRMB { get; set; }
        public string eInvoice { get; set; }
        public string eInoviceNum { get; set; }
        public string VendorEmail { get; set; }
        public string AssetHave { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string AssetSupplyCompany { get; set; }
        public Nullable<decimal> AssetAmount { get; set; }
        public Nullable<int> SAAssetTaskID { get; set; }
    }
}
